{% set name = "plot-av" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plot_av-{{ version }}.tar.gz
  sha256: 3be3fce4fd997faba2997d2fad1b5ecd461da54f03b14c71b444f2319a12053b

build:
  entry_points:
    - plot-av = plot_av.plot_av:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - av
    - matplotlib-base

test:
  imports:
    - plot_av
  commands:
    - pip check
    - plot-av --help
  requires:
    - pip

about:
  home: https://github.com/wangyoucao577/plot-av
  summary: Plot Audio/Video streams for better insights
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wangyoucao577
